version: '3.8'

services:
  web:
    build:
        context: ./app
        dockerfile: Dockerfile.prod
    command: gunicorn challenge_weekbier.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 5000
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - ${NGINX_PORT:-80}:80
    depends_on:
      - web


volumes:
  static_volume:
